'use client';

import { useCallback, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Ban, CheckCircle, ChevronLeft, ChevronRight, FileImage, Menu, RefreshCw, Search, ShieldCheck, Users, X } from 'lucide-react';
import { useAdminAuth } from '@/context/AdminAuthContext';

type Filter='ALL'|'ACTIVE'|'BLOCKED'|'VERIFIED'|'UNVERIFIED'|'ADMINS'; type Section='DASHBOARD'|'USERS'|'CONTENT'|'AUDIT'|'SECURITY';
interface Stats{totalUsers:number;activeUsers:number;blockedUsers:number;verifiedUsers:number;totalPosts:number;activeStories:number;totalCircles:number;newUsersToday:number;newUsersLast7Days:number}
interface AdminUser{userId:string;username:string;email:string;role:string;displayName:string;bio:string;avatarUrl?:string;isActive:boolean;isVerified:boolean;isPrivate:boolean;createdAt:string;postCount:number;followerCount:number;followingCount:number;activeStoryCount:number}
interface UsersPage{users:AdminUser[];currentPage:number;totalItems:number;totalPages:number;pageSize:number}
interface AuditPage{logs:{id:string;adminUserId:string;targetUserId:string;action:string;createdAt:string}[];currentPage:number;totalItems:number;totalPages:number}

function Avatar({user}:{user:AdminUser}){const [failed,setFailed]=useState(false);return user.avatarUrl&&!failed?<img src={user.avatarUrl} onError={()=>setFailed(true)} alt="" className="h-9 w-9 rounded-full object-cover"/>:<span className="grid h-9 w-9 place-items-center rounded-full bg-indigo-600 font-bold">{(user.displayName||user.username).charAt(0).toUpperCase()}</span>}

export default function AdminDashboard(){const {user,loading,api,logout}=useAdminAuth();const router=useRouter();const [section,setSection]=useState<Section>('DASHBOARD'),[mobileNav,setMobileNav]=useState(false);const [stats,setStats]=useState<Stats|null>(null),[usersPage,setUsersPage]=useState<UsersPage|null>(null),[audit,setAudit]=useState<AuditPage|null>(null);const [query,setQuery]=useState(''),[debounced,setDebounced]=useState(''),[filter,setFilter]=useState<Filter>('ALL'),[page,setPage]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<AdminUser|null>(null),[editing,setEditing]=useState(false),[actionError,setActionError]=useState('');const [form,setForm]=useState({username:'',email:'',displayName:'',bio:'',isPrivate:false});
  useEffect(()=>{if(!loading&&!user)router.replace('/login');},[loading,user,router]);
  useEffect(()=>{const id=setTimeout(()=>{setDebounced(query.trim());setPage(0);},300);return()=>clearTimeout(id);},[query]);
  const load=useCallback(async()=>{if(!user)return;setBusy(true);setError('');try{const requests:any[]=[api.get('/admin/stats'),api.get('/admin/users',{params:{query:debounced,filter,page,size:20}})];if(section==='AUDIT')requests.push(api.get('/admin/audit',{params:{page,size:30}}));const [s,u,a]=await Promise.all(requests);setStats(s.data);setUsersPage(u.data);if(a)setAudit(a.data);}catch(reason:any){if(reason.response?.status===401||reason.response?.status===403){logout();router.replace('/login');return;}setError('No se pudo cargar el panel de administración');}finally{setBusy(false);}},[user,api,debounced,filter,page,section,logout,router]);
  useEffect(()=>{void load();},[load]);
  const detail=async(id:string)=>{setActionError('');try{const response=await api.get(`/admin/users/${id}`);setSelected(response.data);setForm({username:response.data.username,email:response.data.email,displayName:response.data.displayName,bio:response.data.bio||'',isPrivate:response.data.isPrivate});setEditing(false);}catch(reason:any){setActionError(reason.response?.data?.message||'No se pudo cargar el usuario.');}};
  const toggle=async(target:AdminUser)=>{setActionError('');setBusy(true);try{await api.post(`/admin/users/${target.userId}/toggle-block`);await load();if(selected?.userId===target.userId)await detail(target.userId);}catch(reason:any){setActionError(reason.response?.data?.message||'No se pudo cambiar el estado.');}finally{setBusy(false);}};
  const save=async()=>{if(!selected)return;setBusy(true);setActionError('');try{const response=await api.patch(`/admin/users/${selected.userId}`,form);setSelected(response.data);setEditing(false);await load();}catch(reason:any){setActionError(reason.response?.data?.message||'No se pudo actualizar el usuario.');}finally{setBusy(false);}};
  if(loading||!user)return <main className="grid min-h-screen place-items-center bg-zinc-950"><RefreshCw className="animate-spin text-indigo-400"/></main>;
  const nav:[Section,string][]=[['DASHBOARD','Dashboard'],['USERS','Usuarios'],['CONTENT','Contenido'],['AUDIT','Auditoría'],['SECURITY','Seguridad']];const cards=stats?[['Usuarios',stats.totalUsers,Users],['Activos',stats.activeUsers,CheckCircle],['Bloqueados',stats.blockedUsers,Ban],['Verificados',stats.verifiedUsers,ShieldCheck],['Contribuciones',stats.totalPosts,FileImage],['Momentos',stats.activeStories,FileImage],['Círculos',stats.totalCircles,Users],['Nuevos hoy',stats.newUsersToday,Users],['Nuevos 7 días',stats.newUsersLast7Days,Users]] as const:[];
  return <main className="min-h-screen bg-zinc-950 text-zinc-100"><aside className={`${mobileNav?'flex':'hidden'} fixed inset-y-0 left-0 z-40 w-64 flex-col border-r border-zinc-800 bg-zinc-950 p-4 md:flex`}><div className="mb-8 flex items-center justify-between"><div><b className="text-lg">Lifonk Admin</b><p className="text-[10px] uppercase text-zinc-500">Operaciones internas</p></div><button onClick={()=>setMobileNav(false)} className="md:hidden"><X/></button></div><nav className="space-y-1">{nav.map(([id,label])=><button key={id} onClick={()=>{setSection(id);setMobileNav(false);}} className={`w-full rounded-xl px-4 py-3 text-left text-sm ${section===id?'bg-indigo-600 font-bold':'text-zinc-400 hover:bg-zinc-900'}`}>{label}</button>)}</nav><div className="mt-auto rounded-xl border border-zinc-800 p-3"><p className="text-sm font-bold">{user.displayName||user.username}</p><p className="text-xs text-zinc-500">@{user.username}</p><button onClick={()=>{logout();router.replace('/login');}} className="mt-3 text-xs text-rose-400">Cerrar sesión</button></div></aside><div className="md:pl-64"><header className="sticky top-0 z-20 flex items-center justify-between border-b border-zinc-800 bg-zinc-950/95 px-5 py-4 backdrop-blur"><div className="flex items-center gap-3"><button onClick={()=>setMobileNav(true)} className="md:hidden"><Menu/></button><div><b>Administrador</b><p className="text-xs text-zinc-500">{nav.find(([id])=>id===section)?.[1]}</p></div></div><button onClick={()=>void load()} disabled={busy} className="flex gap-2 rounded-xl border border-zinc-800 px-3 py-2 text-xs"><RefreshCw className={`h-4 w-4 ${busy?'animate-spin':''}`}/>Actualizar</button></header><div className="p-5 md:p-8">{error?<div className="rounded-2xl border border-rose-900 bg-rose-950/30 p-8 text-center"><p>{error}</p><button onClick={()=>void load()} className="mt-4 rounded-xl bg-indigo-600 px-4 py-2">Reintentar</button></div>:<>
    {(section==='DASHBOARD'||section==='CONTENT'||section==='SECURITY')&&<><section className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-5">{cards.map(([label,value,Icon])=><article key={label} className="rounded-2xl border border-zinc-800 bg-zinc-900 p-4"><Icon className="mb-4 h-4 w-4 text-indigo-400"/><b className="text-2xl">{value}</b><p className="text-[10px] uppercase text-zinc-500">{label}</p></article>)}</section>{section==='CONTENT'&&<p className="mt-6 rounded-2xl border border-zinc-800 p-5 text-sm text-zinc-400">Resumen real de contenido. La moderación detallada permanece limitada al endpoint seguro existente.</p>}{section==='SECURITY'&&<p className="mt-6 rounded-2xl border border-zinc-800 p-5 text-sm text-zinc-400">Las rutas administrativas están protegidas por ROLE_ADMIN y la sesión de esta aplicación es independiente del frontend público.</p>}</>}
    {section==='USERS'&&<section className="overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900"><div className="space-y-3 border-b border-zinc-800 p-4"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-zinc-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar usuario, email o nombre..." className="w-full rounded-xl border border-zinc-700 bg-zinc-950 py-2.5 pl-10 pr-3 text-sm"/></div><div className="flex flex-wrap gap-2">{(['ALL','ACTIVE','BLOCKED','VERIFIED','UNVERIFIED','ADMINS'] as Filter[]).map(value=><button key={value} onClick={()=>{setFilter(value);setPage(0);}} className={`rounded-lg px-3 py-1.5 text-xs ${filter===value?'bg-indigo-600':'bg-zinc-800 text-zinc-400'}`}>{value}</button>)}</div></div>{actionError&&<p className="bg-rose-950/40 p-3 text-xs text-rose-300">{actionError}</p>}<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="text-zinc-500"><tr>{['Usuario','Email','Rol','Estado','Privacidad','Contribuciones','Conexiones','Acción'].map(label=><th key={label} className="p-3">{label}</th>)}</tr></thead><tbody className="divide-y divide-zinc-800">{usersPage?.users.map(target=><tr key={target.userId} onClick={()=>void detail(target.userId)} className="cursor-pointer hover:bg-zinc-800/50"><td className="p-3"><div className="flex items-center gap-2"><Avatar user={target}/><span><b>@{target.username}</b><small className="block text-zinc-500">{target.displayName}</small></span></div></td><td className="p-3">{target.email}</td><td className="p-3">{target.role}</td><td className="p-3">{target.isActive?'Activa':'Bloqueada'} · {target.isVerified?'Verificada':'No verificada'}</td><td className="p-3">{target.isPrivate?'Privada':'Pública'}</td><td className="p-3">{target.postCount}</td><td className="p-3">{target.followerCount}</td><td className="p-3"><button onClick={event=>{event.stopPropagation();void toggle(target);}} disabled={busy||target.userId===user.userId} className="rounded-lg border border-zinc-700 px-3 py-1.5 disabled:opacity-30">{target.isActive?'Bloquear':'Desbloquear'}</button></td></tr>)}</tbody></table></div><footer className="flex justify-between border-t border-zinc-800 p-4 text-xs"><span>{usersPage?.totalItems||0} usuarios</span><div className="flex items-center gap-3"><button disabled={page===0} onClick={()=>setPage(value=>value-1)}><ChevronLeft/></button><span>{usersPage?.totalPages?`${page+1}/${usersPage.totalPages}`:'0/0'}</span><button disabled={!usersPage||page+1>=usersPage.totalPages} onClick={()=>setPage(value=>value+1)}><ChevronRight/></button></div></footer></section>}
    {section==='AUDIT'&&<section className="overflow-hidden rounded-2xl border border-zinc-800"><table className="w-full text-left text-xs"><thead><tr className="text-zinc-500"><th className="p-3">Acción</th><th>Administrador</th><th>Objetivo</th><th>Fecha</th></tr></thead><tbody className="divide-y divide-zinc-800">{audit?.logs.map(log=><tr key={log.id}><td className="p-3 font-bold">{log.action}</td><td>{log.adminUserId}</td><td>{log.targetUserId}</td><td>{new Date(log.createdAt).toLocaleString()}</td></tr>)}</tbody></table>{audit&&!audit.logs.length&&<p className="p-10 text-center text-zinc-500">No hay acciones administrativas registradas.</p>}</section>}
  </>}</div></div>
  {selected&&<div className="fixed inset-0 z-50 flex justify-end bg-black/70" onClick={()=>setSelected(null)}><aside className="h-full w-full max-w-lg overflow-y-auto border-l border-zinc-800 bg-zinc-950 p-6" onClick={event=>event.stopPropagation()}><button onClick={()=>setSelected(null)} className="float-right"><X/></button><div className="mb-6 flex items-center gap-3"><Avatar user={selected}/><div><h2 className="font-black">{selected.displayName}</h2><p className="text-zinc-500">@{selected.username}</p></div></div>{editing?<div className="space-y-3">{(['username','email','displayName','bio'] as const).map(key=><label key={key} className="block text-xs text-zinc-400">{key}<input value={form[key]} onChange={event=>setForm({...form,[key]:event.target.value})} className="mt-1 w-full rounded-xl border border-zinc-700 bg-zinc-900 p-3"/></label>)}<label className="flex gap-2"><input type="checkbox" checked={form.isPrivate} onChange={event=>setForm({...form,isPrivate:event.target.checked})}/>Espacio privado</label><button disabled={busy} onClick={()=>void save()} className="rounded-xl bg-indigo-600 px-4 py-2">Guardar</button></div>:<div className="space-y-4"><dl className="grid grid-cols-2 gap-3 rounded-xl bg-zinc-900 p-4">{[['Email',selected.email],['Rol',selected.role],['Estado',selected.isActive?'Activa':'Bloqueada'],['Privacidad',selected.isPrivate?'Privada':'Pública'],['Contribuciones',selected.postCount],['Momentos',selected.activeStoryCount],['Conexiones',selected.followerCount],['Conexiones activas',selected.followingCount]].map(([key,value])=><div key={String(key)}><dt className="text-[10px] uppercase text-zinc-500">{key}</dt><dd>{value}</dd></div>)}</dl><div className="flex gap-2"><button onClick={()=>setEditing(true)} className="rounded-xl bg-indigo-600 px-4 py-2">Editar</button><button disabled={busy||selected.userId===user.userId} onClick={()=>void toggle(selected)} className="rounded-xl border border-rose-800 px-4 py-2 text-rose-400 disabled:opacity-30">{selected.isActive?'Bloquear':'Desbloquear'}</button></div></div>}</aside></div>}
  </main>;
}
