export type DiscoverTopic = {
  slug: string; label: string; emoji: string; description: string; accent: string;
  keywords: string[]; highlights: string[]; circles: string[];
};

export const DISCOVER_TOPICS: DiscoverTopic[] = [
  { slug:'tecnologia', label:'Tecnología', emoji:'💻', description:'IA, gadgets, software, internet e innovación.', accent:'from-cyan-500 to-blue-600', keywords:['tecnología','tecnologia','ia','inteligencia artificial','software','gadget','internet','app'], highlights:['IA y herramientas','Software que cambia hábitos','Gadgets e innovación'], circles:['IA práctica','Tecnología cotidiana','Futuro digital'] },
  { slug:'gaming', label:'Gaming', emoji:'🎮', description:'PC, consolas, eSports, lanzamientos y comunidades.', accent:'from-violet-500 to-indigo-600', keywords:['gaming','videojuego','juego','esports','pc gamer','playstation','xbox','nintendo'], highlights:['Lanzamientos','Competitivo y eSports','Setup y hardware'], circles:['Gaming LATAM','PC & Consolas','eSports'] },
  { slug:'musica', label:'Música', emoji:'🎵', description:'Artistas, canciones, producción, instrumentos y géneros.', accent:'from-fuchsia-500 to-rose-500', keywords:['música','musica','canción','cancion','artista','album','álbum','playlist','guitarra'], highlights:['Nuevos sonidos','Producción musical','Recomendaciones'], circles:['Descubrimiento musical','Productores','Instrumentistas'] },
  { slug:'anime', label:'Anime & Manga', emoji:'⛩️', description:'Series, manga, teorías, personajes, arte y recomendaciones.', accent:'from-pink-500 to-orange-500', keywords:['anime','manga','otaku','shonen','seinen','cosplay'], highlights:['Temporada actual','Teorías y debates','Manga y arte'], circles:['Anime semanal','Manga','Teorías'] },
  { slug:'fotografia', label:'Fotografía', emoji:'📷', description:'Capturas, edición, cámaras, composición y fotografía móvil.', accent:'from-slate-500 to-zinc-800', keywords:['foto','fotografía','fotografia','cámara','camara','lightroom','retrato','paisaje'], highlights:['Composición','Edición','Fotografía móvil'], circles:['Foto móvil','Retratos','Paisajes'] },
  { slug:'ciencia', label:'Ciencia', emoji:'🔬', description:'Astronomía, física, biología, espacio e investigación.', accent:'from-emerald-500 to-teal-600', keywords:['ciencia','astronomía','astronomia','física','fisica','biología','biologia','espacio','investigación'], highlights:['Universo','Vida y biología','Descubrimientos'], circles:['Ciencia para todos','Astronomía','Curiosidad científica'] },
  { slug:'viajes', label:'Viajes', emoji:'✈️', description:'Destinos, rutas, culturas, comida y experiencias reales.', accent:'from-sky-500 to-teal-500', keywords:['viaje','viajes','destino','turismo','ruta','mochilero','vacaciones'], highlights:['Destinos','Rutas y presupuesto','Cultura local'], circles:['Viajeros','Mochileros','Rutas del mundo'] },
  { slug:'fitness', label:'Fitness & Bienestar', emoji:'💪', description:'Entrenamiento, hábitos, deporte, nutrición general y bienestar.', accent:'from-lime-500 to-emerald-600', keywords:['fitness','gym','entrenamiento','deporte','bienestar','rutina','nutrición','nutricion'], highlights:['Entrenamiento','Hábitos sostenibles','Bienestar'], circles:['Entrenamiento','Hábitos saludables','Deporte'] },
  { slug:'arte', label:'Arte & Diseño', emoji:'🎨', description:'Ilustración, UI/UX, arquitectura, diseño y creatividad.', accent:'from-amber-500 to-rose-500', keywords:['arte','diseño','diseño','ui','ux','ilustración','ilustracion','arquitectura','creatividad'], highlights:['Ilustración','UI/UX','Arquitectura y diseño'], circles:['Diseñadores','Ilustración','UI/UX'] },
  { slug:'programacion', label:'Programación', emoji:'👨‍💻', description:'Java, JavaScript, Python, backend, frontend y proyectos.', accent:'from-teal-500 to-cyan-600', keywords:['programación','programacion','java','javascript','python','backend','frontend','react','spring','código','codigo'], highlights:['Backend','Frontend','Proyectos y aprendizaje'], circles:['Java & Spring','Web Dev','Proyectos de código'] },
  { slug:'cine', label:'Cine & Series', emoji:'🎬', description:'Películas, series, estrenos, recomendaciones y análisis.', accent:'from-red-500 to-orange-600', keywords:['cine','película','pelicula','serie','netflix','hbo','estreno','director'], highlights:['Estrenos','Recomendaciones','Análisis y debates'], circles:['Cinéfilos','Series','Películas de culto'] },
  { slug:'naturaleza', label:'Naturaleza', emoji:'🌿', description:'Animales, ecología, senderismo, paisajes y medioambiente.', accent:'from-green-500 to-emerald-700', keywords:['naturaleza','bosque','animal','ecología','ecologia','senderismo','paisaje','medioambiente'], highlights:['Vida silvestre','Senderismo','Ecología'], circles:['Naturaleza','Senderismo','Vida silvestre'] },
];

export const TOPIC_BY_SLUG = Object.fromEntries(DISCOVER_TOPICS.map(topic => [topic.slug, topic])) as Record<string, DiscoverTopic>;
