import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, RefreshControl, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from '../context/AuthContext';
import { useAppTheme } from '../theme';
import UserAvatar from '../components/UserAvatar';

interface Notification { notificationId:string;senderUsername:string;senderDisplayName:string;senderAvatarUrl?:string;notificationType:string;targetId:string;messagePreview?:string;isRead:boolean;createdAt:string }
const relativeTime=(value:string)=>{const time=new Date(value).getTime();if(!Number.isFinite(time))return'';const seconds=Math.max(0,Math.floor((Date.now()-time)/1000));if(seconds<60)return'Ahora';if(seconds<3600)return`Hace ${Math.floor(seconds/60)} min`;if(seconds<86400)return`Hace ${Math.floor(seconds/3600)} h`;if(seconds<172800)return'Ayer';return new Intl.DateTimeFormat('es',{day:'numeric',month:'short'}).format(new Date(time));};
const copy=(type:string)=>type==='LIKE_POST'?'resonó con tu contribución.':type==='COMMENT'?'dejó un eco en tu contribución.':type==='FOLLOW'?'conectó contigo.':type==='FOLLOW_REQUEST'?'quiere conectar contigo.':type==='STORY_REPLY'?'respondió a tu momento.':type==='STORY_REACTION'?'reaccionó a tu momento.':'generó una nueva señal.';

export default function NotificationsScreen({onOpenProfile,onOpenPost}:{onOpenProfile?:(username:string)=>void;onOpenPost?:(postId:string)=>void}) {
  const {api}=useAuth();const {theme}=useAppTheme();const [items,setItems]=useState<Notification[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState('');
  const load=useCallback(async()=>{try{const res=await api.get('/notifications');setItems((res.data||[]).filter((item:Notification)=>item.notificationType!=='MESSAGE'));setError('');}catch(requestError){console.error(requestError);setError('No se pudieron cargar las señales.');}finally{setLoading(false);setRefreshing(false);}},[api]);
  useEffect(()=>{void load();},[load]);
  const read=async(item:Notification)=>{if(item.isRead)return true;try{await api.patch(`/notifications/${item.notificationId}/read`);setItems(old=>old.map(value=>value.notificationId===item.notificationId?{...value,isRead:true}:value));return true;}catch(requestError){console.error(requestError);setError('No se pudo marcar la señal como leída.');return false;}};
  const open=async(item:Notification)=>{if(!await read(item))return;if(['LIKE_POST','COMMENT'].includes(item.notificationType))onOpenPost?.(item.targetId);else if(['FOLLOW','FOLLOW_REQUEST'].includes(item.notificationType))onOpenProfile?.(item.senderUsername);};
  const request=async(item:Notification,action:'accept'|'reject')=>{try{await api.post(`/social/requests/${item.targetId}/${action}`);await load();}catch(requestError:any){console.error(requestError);if(requestError.response?.status===404)void load();else setError(`No se pudo ${action==='accept'?'aceptar':'rechazar'} la solicitud.`);}};
  if(loading)return <View style={[styles.center,{backgroundColor:theme.background}]}><ActivityIndicator color={theme.accent}/></View>;
  const unread=items.filter(item=>!item.isRead).length;
  return <View style={[styles.container,{backgroundColor:theme.background}]}><View style={[styles.header,{borderColor:theme.border}]}><Text style={[styles.title,{color:theme.textPrimary}]}>Señales</Text>{unread?<View style={[styles.badge,{backgroundColor:theme.primary}]}><Text style={styles.badgeText}>{unread}</Text></View>:null}</View>{error?<TouchableOpacity onPress={()=>setError('')} style={styles.error}><Text style={styles.errorText}>{error}</Text></TouchableOpacity>:null}<FlatList data={items} keyExtractor={item=>item.notificationId} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load();}} tintColor={theme.accent}/>} renderItem={({item})=><TouchableOpacity onPress={()=>void open(item)} style={[styles.card,{borderColor:theme.border},!item.isRead&&{backgroundColor:theme.surfaceSecondary}]}><UserAvatar avatarUrl={item.senderAvatarUrl} displayName={item.senderDisplayName} username={item.senderUsername} size={40}/><View style={{flex:1}}><Text style={{color:theme.textSecondary,fontSize:13,lineHeight:18}}><Text style={{color:theme.textPrimary,fontWeight:'800'}}>@{item.senderUsername} </Text>{copy(item.notificationType)}</Text><Text style={{color:theme.textMuted,fontSize:11,marginTop:3}}>{relativeTime(item.createdAt)}</Text>{item.notificationType==='FOLLOW_REQUEST'?<View style={styles.actions}><TouchableOpacity onPress={()=>void request(item,'accept')} style={[styles.action,{backgroundColor:theme.primary}]}><Text style={styles.actionText}>Aceptar</Text></TouchableOpacity><TouchableOpacity onPress={()=>void request(item,'reject')} style={[styles.action,{borderWidth:1,borderColor:theme.border}]}><Text style={{color:theme.textPrimary,fontWeight:'800',fontSize:11}}>Rechazar</Text></TouchableOpacity></View>:null}</View>{!item.isRead?<View style={styles.read}><View style={[styles.dot,{backgroundColor:theme.accent}]}/><TouchableOpacity accessibilityLabel="Marcar señal como leída" onPress={event=>{event.stopPropagation();void read(item);}} style={styles.close}><Text style={{color:theme.textMuted,fontSize:23}}>×</Text></TouchableOpacity></View>:null}</TouchableOpacity>} contentContainerStyle={!items.length?styles.emptyContainer:styles.list} ListEmptyComponent={<View style={styles.empty}><Ionicons name="notifications-outline" size={42} color={theme.textMuted}/><Text style={{color:theme.textPrimary,fontWeight:'800',marginTop:10}}>No tienes señales nuevas</Text></View>}/></View>;
}
const styles=StyleSheet.create({container:{flex:1},center:{flex:1,alignItems:'center',justifyContent:'center'},header:{height:58,paddingHorizontal:18,borderBottomWidth:1,flexDirection:'row',alignItems:'center',gap:9},title:{fontSize:21,fontWeight:'900'},badge:{minWidth:22,height:22,borderRadius:11,alignItems:'center',justifyContent:'center'},badgeText:{color:'#fff',fontSize:11,fontWeight:'900'},error:{backgroundColor:'#7f1d1d',padding:9},errorText:{color:'#fee2e2',textAlign:'center'},list:{paddingHorizontal:15},card:{flexDirection:'row',alignItems:'flex-start',gap:11,paddingVertical:14,borderBottomWidth:1},read:{alignItems:'center',gap:3},dot:{width:8,height:8,borderRadius:4},close:{width:32,height:32,alignItems:'center',justifyContent:'center'},actions:{flexDirection:'row',gap:8,marginTop:9},action:{paddingHorizontal:13,paddingVertical:7,borderRadius:9},actionText:{color:'#fff',fontWeight:'800',fontSize:11},emptyContainer:{flexGrow:1,justifyContent:'center'},empty:{alignItems:'center'}});
