import React, { useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Image, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useVideoPlayer, VideoView } from 'expo-video';
import { useAuth } from '../context/AuthContext';
import { useAppTheme } from '../theme';
import UserAvatar from '../components/UserAvatar';

function PostVideo({ url }: { url:string }) {
  const player = useVideoPlayer(url);
  useEffect(() => () => player.pause(), [player]);
  return <VideoView player={player} style={styles.media} nativeControls contentFit="contain"/>;
}

export default function PostDetailScreen({ postId, onBack, onOpenProfile }: { postId:string; onBack:()=>void; onOpenProfile:(username:string)=>void }) {
  const { api }=useAuth(); const { theme }=useAppTheme();
  const [post,setPost]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[comments,setComments]=useState<any[]>([]),[commentText,setCommentText]=useState('');
  const load=async()=>{setLoading(true);try{const [postRes,commentRes]=await Promise.all([api.get(`/posts/${postId}`),api.get(`/comments/${postId}`)]);setPost(postRes.data);setComments(commentRes.data||[]);setError('');}catch(requestError:any){console.error(requestError);setPost(null);setError(requestError.response?.status===403?'No tienes acceso a esta publicación.':requestError.response?.status===404?'Publicación no encontrada.':'No se pudo cargar la publicación.');}finally{setLoading(false);}};
  const like=async()=>{try{const res=await api.post(`/likes/${postId}`);setPost((old:any)=>({...old,hasLiked:res.data.liked,likesCount:res.data.count}));}catch{setError('No se pudo actualizar el Me gusta.');}};
  const save=async()=>{try{const res=await api.post(`/posts/${postId}/save`);setPost((old:any)=>({...old,isSaved:res.data.saved}));}catch{setError('No se pudo actualizar Guardados.');}};
  const comment=async()=>{if(!commentText.trim())return;try{const res=await api.post(`/comments/${postId}`,{content:commentText.trim()});setComments(old=>[...old,res.data]);setCommentText('');setPost((old:any)=>({...old,commentsCount:(old.commentsCount||0)+1}));}catch{setError('No se pudo publicar el comentario. Conservamos tu texto.');}};
  useEffect(()=>{void load();},[postId]);
  const content=post?[{type:'post',id:'post'},...comments.map(value=>({type:'comment',id:value.commentId,value}))]:[];
  return <View style={[styles.container,{backgroundColor:theme.background}]}><View style={[styles.header,{borderColor:theme.border}]}><TouchableOpacity onPress={onBack}><Ionicons name="arrow-back" size={24} color={theme.textPrimary}/></TouchableOpacity><Text style={[styles.title,{color:theme.textPrimary}]}>Publicación</Text></View>{loading?<ActivityIndicator style={{marginTop:40}} color={theme.accent}/>:error&&!post?<View style={styles.center}><Text style={{color:theme.textSecondary}}>{error}</Text><TouchableOpacity onPress={()=>void load()}><Text style={{color:theme.accent,marginTop:12}}>Reintentar</Text></TouchableOpacity></View>:post?<FlatList data={content} keyExtractor={item=>item.id} renderItem={({item}:any)=>item.type==='post'?<View style={styles.content}><TouchableOpacity onPress={()=>onOpenProfile(post.username)} style={styles.author}><UserAvatar avatarUrl={post.avatarUrl} displayName={post.displayName} username={post.username} size={42}/><View><Text style={{color:theme.textPrimary,fontWeight:'800'}}>{post.displayName||post.username}</Text><Text style={{color:theme.textMuted}}>@{post.username}</Text></View></TouchableOpacity>{post.caption?<Text style={{color:theme.textPrimary,lineHeight:21}}>{post.caption}</Text>:null}{post.mediaUrls?.map((url:string,index:number)=>post.mediaTypes?.[index]==='VIDEO'?<PostVideo key={url} url={url}/>:<Image key={url} source={{uri:url}} style={styles.media} resizeMode="contain"/>)}<View style={styles.actions}><TouchableOpacity onPress={()=>void like()}><Text style={{color:post.hasLiked?theme.danger:theme.textMuted}}>♥ {post.likesCount}</Text></TouchableOpacity><Text style={{color:theme.textMuted}}>Comentarios {post.commentsCount}</Text><TouchableOpacity onPress={()=>void save()}><Ionicons name={post.isSaved?'bookmark':'bookmark-outline'} size={21} color={post.isSaved?theme.accent:theme.textMuted}/></TouchableOpacity></View>{error?<Text style={{color:theme.danger}}>{error}</Text>:null}<View style={styles.composer}><TextInput value={commentText} onChangeText={setCommentText} placeholder="Escribe un comentario…" placeholderTextColor={theme.textMuted} style={[styles.input,{color:theme.textPrimary,backgroundColor:theme.surface,borderColor:theme.border}]}/><TouchableOpacity onPress={()=>void comment()}><Ionicons name="send" size={21} color={theme.accent}/></TouchableOpacity></View></View>:<View style={styles.comment}><UserAvatar avatarUrl={item.value.avatarUrl} displayName={item.value.displayName} username={item.value.username} size={32}/><View style={{flex:1}}><Text style={{color:theme.textPrimary,fontWeight:'800'}}>@{item.value.username}</Text><Text style={{color:theme.textSecondary}}>{item.value.content}</Text></View></View>} contentContainerStyle={{paddingBottom:22}}/>:null}</View>;
}
const styles=StyleSheet.create({container:{flex:1},header:{height:54,flexDirection:'row',alignItems:'center',gap:16,paddingHorizontal:16,borderBottomWidth:1},title:{fontSize:18,fontWeight:'800'},center:{flex:1,alignItems:'center',justifyContent:'center',padding:24},content:{padding:18,gap:16},author:{flexDirection:'row',alignItems:'center',gap:10},media:{width:'100%',height:420,borderRadius:18,backgroundColor:'#000'},actions:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},composer:{flexDirection:'row',alignItems:'center',gap:9},input:{flex:1,height:42,borderWidth:1,borderRadius:21,paddingHorizontal:14},comment:{paddingHorizontal:18,paddingVertical:10,flexDirection:'row',gap:9}});
